baseURL = 'https://oskalon.com'
languageCode = 'en-us'
paginate = 6
theme= "coHub"
title = 'OSKALON'
 
[Menu]
  # Main Menu
  [[menu.Main]]
  name = "Exibition"
  url= "#gallery"
  weight = 1
  [[menu.Main]]
  name = "Feature"
  url= "#service"
  weight = 1
  [[menu.Main]]
  name = "About"
  url= "/about/"
  weight = 3
  [[menu.Main]]
  name = "Blog"
  url= "#blog"
  weight = 4
  [[menu.Main]]
  name = "Pricing"
  url= "#pricing"
  weight = 5
  [[menu.Main]]
  name = "FAQ"
  url= "#faq"
  weight = 6
  [[menu.Main]]
  name = "Contact"
  url= "/contact/"
  weight = 7

  # Sitemap Menu
  [[menu.sitemap]]
  name = "Privacy Policy"
  url = "/privacy/"
  weight = 1
  [[menu.sitemap]]
  name = "Terms"
  url = "/terms/"
  weight = 2


[params]
  aboutPageURL = "blog"
  contactLink = "contact"
  copyright = "© {year} Oskalon"
  fabFormURL =  "https://"
  googleAnalytics = ""
  logo = "images/logo.png"
  footerlogo = "images/logo.png"
  footerDescription = ""

  [params.address]
  address = "Oskalon DOO"
  email = "info@oskalon.com"
  openingDesc = ""
  openingHours = ""
  phone = ""

  [params.map]
  APIkey = "AIzaSyC9rV6yesIygoVKTD6QLf_iCa9eiIIHqZ0"
  latitude = "45.4502528"
  longitude = "-122.783407"
  pinImage = "images/pin.png"

  # Socail icons
  [[params.social]]
  icon = "ti-facebook"
  url = "https://www.facebook.com/"
  weight = 1
  [[params.social]]
  icon = "ti-twitter-alt"
  url = "https://twitter.com/"
  weight = 2
  [[params.social]]
  icon = "ti-dribbble"
  url = "https://dribbble.com/"
  weight = 3
  [[params.social]]
  icon = "ti-instagram"
  url = "https://www.instagram.com/"
  weight = 4
  
  
